CREATE TABLE produto (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(500),
    preco DECIMAL(10,2) NOT NULL,
    categoria VARCHAR(100),
    origem VARCHAR(50) DEFAULT 'LOCAL',
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
